/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IElkRouter } from "./IElkRouter";
export type { IWAVAX } from "./IWAVAX";
