/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IElkCallee,
  IElkCalleeInterface,
} from "../../../../../../@elkdex/avax-exchange-contracts/contracts/elk-core/interfaces/IElkCallee";
import { Contract, Interface, type ContractRunner } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "elkCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IElkCallee__factory {
  static readonly abi = _abi;
  static createInterface(): IElkCalleeInterface {
    return new Interface(_abi) as IElkCalleeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IElkCallee {
    return new Contract(address, _abi, runner) as unknown as IElkCallee;
  }
}
