/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as elkCore from "./elk-core";
import type * as elkPeriphery from "./elk-periphery";

export type { elkCore };

export type { elkPeriphery };
