/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20__factory } from "./IERC20__factory";
export { IElkRouter__factory } from "./IElkRouter__factory";
export { IWAVAX__factory } from "./IWAVAX__factory";
