/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as interfaces from "./interfaces";

export type { interfaces };
export type { ElkERC20 } from "./ElkERC20";
export type { ElkPair } from "./ElkPair";
