/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IElkDexOracle__factory } from "./IElkDexOracle__factory";
export { IElkERC20__factory } from "./IElkERC20__factory";
export { IElkFactory__factory } from "./IElkFactory__factory";
export { IElkPair__factory } from "./IElkPair__factory";
export { IElkV2FarmFactory__factory } from "./IElkV2FarmFactory__factory";
export { IElkV2FarmManager__factory } from "./IElkV2FarmManager__factory";
export { IElkV2FarmingRewards__factory } from "./IElkV2FarmingRewards__factory";
export { IElkV2FarmingRewardsPermissioned__factory } from "./IElkV2FarmingRewardsPermissioned__factory";
export { IStakeFactory__factory } from "./IStakeFactory__factory";
export { IStakeManager__factory } from "./IStakeManager__factory";
export { IStaking__factory } from "./IStaking__factory";
export { IStakingFee__factory } from "./IStakingFee__factory";
export { IStakingRewards__factory } from "./IStakingRewards__factory";
