/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";

export interface IElkV2FarmManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRewardToken"
      | "multiClaim"
      | "recoverERC20"
      | "recoverFees"
      | "recoverLeftoverCoverage"
      | "recoverLeftoverReward"
      | "setFarmFactory"
      | "startEmission"
      | "startEmissionWithCoverage"
      | "stopEmission"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FarmFactorySet" | "RewardsReceived"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addRewardToken",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "multiClaim",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverERC20",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverLeftoverCoverage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverLeftoverReward",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFarmFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startEmission",
    values: [AddressLike, BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startEmissionWithCoverage",
    values: [AddressLike, BigNumberish[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stopEmission",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addRewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multiClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoverERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverLeftoverCoverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverLeftoverReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFarmFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startEmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startEmissionWithCoverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopEmission",
    data: BytesLike
  ): Result;
}

export namespace FarmFactorySetEvent {
  export type InputTuple = [factoryAddress: AddressLike];
  export type OutputTuple = [factoryAddress: string];
  export interface OutputObject {
    factoryAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsReceivedEvent {
  export type InputTuple = [farm: AddressLike];
  export type OutputTuple = [farm: string];
  export interface OutputObject {
    farm: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IElkV2FarmManager extends BaseContract {
  connect(runner?: ContractRunner | null): IElkV2FarmManager;
  waitForDeployment(): Promise<this>;

  interface: IElkV2FarmManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRewardToken: TypedContractMethod<
    [_farmAddress: AddressLike, _tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  multiClaim: TypedContractMethod<
    [_farms: AddressLike[]],
    [void],
    "nonpayable"
  >;

  recoverERC20: TypedContractMethod<
    [
      _farmAddress: AddressLike,
      _tokenAddress: AddressLike,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  recoverFees: TypedContractMethod<
    [_farmAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  recoverLeftoverCoverage: TypedContractMethod<
    [_farmAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  recoverLeftoverReward: TypedContractMethod<
    [_farmAddress: AddressLike, _tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setFarmFactory: TypedContractMethod<
    [_factoryAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  startEmission: TypedContractMethod<
    [
      _farmAddress: AddressLike,
      _rewards: BigNumberish[],
      _duration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  startEmissionWithCoverage: TypedContractMethod<
    [
      _farmAddress: AddressLike,
      _rewards: BigNumberish[],
      _coverage: BigNumberish,
      _duration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  stopEmission: TypedContractMethod<
    [_farmAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRewardToken"
  ): TypedContractMethod<
    [_farmAddress: AddressLike, _tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "multiClaim"
  ): TypedContractMethod<[_farms: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recoverERC20"
  ): TypedContractMethod<
    [
      _farmAddress: AddressLike,
      _tokenAddress: AddressLike,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recoverFees"
  ): TypedContractMethod<[_farmAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recoverLeftoverCoverage"
  ): TypedContractMethod<[_farmAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recoverLeftoverReward"
  ): TypedContractMethod<
    [_farmAddress: AddressLike, _tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFarmFactory"
  ): TypedContractMethod<[_factoryAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startEmission"
  ): TypedContractMethod<
    [
      _farmAddress: AddressLike,
      _rewards: BigNumberish[],
      _duration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startEmissionWithCoverage"
  ): TypedContractMethod<
    [
      _farmAddress: AddressLike,
      _rewards: BigNumberish[],
      _coverage: BigNumberish,
      _duration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stopEmission"
  ): TypedContractMethod<[_farmAddress: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FarmFactorySet"
  ): TypedContractEvent<
    FarmFactorySetEvent.InputTuple,
    FarmFactorySetEvent.OutputTuple,
    FarmFactorySetEvent.OutputObject
  >;
  getEvent(
    key: "RewardsReceived"
  ): TypedContractEvent<
    RewardsReceivedEvent.InputTuple,
    RewardsReceivedEvent.OutputTuple,
    RewardsReceivedEvent.OutputObject
  >;

  filters: {
    "FarmFactorySet(address)": TypedContractEvent<
      FarmFactorySetEvent.InputTuple,
      FarmFactorySetEvent.OutputTuple,
      FarmFactorySetEvent.OutputObject
    >;
    FarmFactorySet: TypedContractEvent<
      FarmFactorySetEvent.InputTuple,
      FarmFactorySetEvent.OutputTuple,
      FarmFactorySetEvent.OutputObject
    >;

    "RewardsReceived(address)": TypedContractEvent<
      RewardsReceivedEvent.InputTuple,
      RewardsReceivedEvent.OutputTuple,
      RewardsReceivedEvent.OutputObject
    >;
    RewardsReceived: TypedContractEvent<
      RewardsReceivedEvent.InputTuple,
      RewardsReceivedEvent.OutputTuple,
      RewardsReceivedEvent.OutputObject
    >;
  };
}
