/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IElkDexOracle } from "./IElkDexOracle";
export type { IElkERC20 } from "./IElkERC20";
export type { IElkFactory } from "./IElkFactory";
export type { IElkPair } from "./IElkPair";
export type { IElkV2FarmFactory } from "./IElkV2FarmFactory";
export type { IElkV2FarmManager } from "./IElkV2FarmManager";
export type { IElkV2FarmingRewards } from "./IElkV2FarmingRewards";
export type { IElkV2FarmingRewardsPermissioned } from "./IElkV2FarmingRewardsPermissioned";
export type { IStakeFactory } from "./IStakeFactory";
export type { IStakeManager } from "./IStakeManager";
export type { IStaking } from "./IStaking";
export type { IStakingFee } from "./IStakingFee";
export type { IStakingRewards } from "./IStakingRewards";
