/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IElkCallee } from "./IElkCallee";
export type { IElkERC20 } from "./IElkERC20";
export type { IElkFactory } from "./IElkFactory";
export type { IElkPair } from "./IElkPair";
