/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as elkV2FarmingRewardsPermissonedSol from "./ElkV2FarmingRewardsPermissoned.sol";
import type * as interfaces from "./interfaces";
import type * as test from "./test";

export type { elkV2FarmingRewardsPermissonedSol };

export type { interfaces };

export type { test };
export type { ElkDexOracle } from "./ElkDexOracle";
export type { ElkV2FarmFactory } from "./ElkV2FarmFactory";
export type { ElkV2FarmManager } from "./ElkV2FarmManager";
export type { ElkV2FarmingRewards } from "./ElkV2FarmingRewards";
export type { StakeFactory } from "./StakeFactory";
export type { StakeManager } from "./StakeManager";
export type { Staking } from "./Staking";
export type { StakingFee } from "./StakingFee";
export type { StakingRewards } from "./StakingRewards";
