/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as avaxExchangeContracts from "./avax-exchange-contracts";

export type { avaxExchangeContracts };
